// 파자(破字) 학습 데이터 — 한자능력검정시험 8급 배정한자 50자
// char: 한자, writer: HanziWriter 애니메이션용 코드(차이날 때만 지정), meaning: 훈(뜻), sound: 음(소리)
// stroke: 총 획수, radical: 부수, type: 육서 분류(상형/지사/회의/형성)
// decomposable: 부수 조합으로 나눌 수 있는 글자인지
// parts: 구성요소 [{char, meaning}], note: 파자 설명(표준적으로 널리 쓰이는 해석/기억법)
// word: 관련 단어 예시 {text, meaning}
const HANJA_DATA = [
  // ── 숫자 ──
  { char:'一', meaning:'한', sound:'일', stroke:1, radical:'一', type:'지사', category:'숫자',
    decomposable:false, parts:[], note:'가로획 하나로 수의 시작인 "하나"를 나타낸 지사문자예요. 더는 나눌 수 없는 가장 기본 글자예요.',
    word:{ text:'一等', meaning:'일등' } },
  { char:'二', meaning:'두', sound:'이', stroke:2, radical:'二', type:'지사', category:'숫자',
    decomposable:false, parts:[], note:'가로획 두 개를 나란히 그어 "둘"을 나타낸 지사문자예요.',
    word:{ text:'二重', meaning:'이중' } },
  { char:'三', meaning:'석', sound:'삼', stroke:3, radical:'一', type:'지사', category:'숫자',
    decomposable:false, parts:[], note:'가로획 세 개로 "셋"을 나타낸 지사문자예요.',
    word:{ text:'三月', meaning:'3월' } },
  { char:'四', meaning:'넉', sound:'사', stroke:5, radical:'囗', type:'회의', category:'숫자',
    decomposable:true, parts:[{char:'囗',meaning:'에워쌀 위(울타리)'},{char:'儿',meaning:'어진사람 인'}],
    note:'흔히 "울타리(囗) 안에 사람(儿)이 넷"이라고 풀어 외우는 글자예요. 원래는 코에서 숨이 나가는 모습을 본떴다는 설도 있어요.',
    word:{ text:'四寸', meaning:'사촌' } },
  { char:'五', meaning:'다섯', sound:'오', stroke:4, radical:'二', type:'지사', category:'숫자',
    decomposable:false, parts:[], note:'하늘과 땅(二) 사이에 다섯 가지 기운이 교차하는 모습(X)을 본뜬 지사문자예요.',
    word:{ text:'五月', meaning:'5월' } },
  { char:'六', meaning:'여섯', sound:'육', stroke:4, radical:'八', type:'상형', category:'숫자',
    decomposable:true, parts:[{char:'亠',meaning:'지붕(돼지해머리)'},{char:'八',meaning:'여덟 팔(나누다)'}],
    note:'재미있게 외우는 방법으로 "지붕(亠) 아래에서 여덟(八)처럼 나누다"로 풀기도 해요. 원래는 움집 모양을 본뜬 상형문자라는 설이 유력해요.',
    word:{ text:'六月', meaning:'6월' } },
  { char:'七', meaning:'일곱', sound:'칠', stroke:2, radical:'一', type:'지사', category:'숫자',
    decomposable:false, parts:[], note:'원래 十(열 십) 모양에서 세로획을 구부려 "자르다"는 뜻을 나타낸 지사문자였는데, 나중에 숫자 "일곱"으로 빌려 쓰게 됐어요.',
    word:{ text:'七十', meaning:'70' } },
  { char:'八', meaning:'여덟', sound:'팔', stroke:2, radical:'八', type:'상형', category:'숫자',
    decomposable:false, parts:[], note:'무언가를 둘로 나눈 모습을 본뜬 상형문자예요. "나누다"는 뜻에서 숫자 "여덟"으로 쓰이게 됐어요.',
    word:{ text:'八月', meaning:'8월' } },
  { char:'九', meaning:'아홉', sound:'구', stroke:2, radical:'乙', type:'지사', category:'숫자',
    decomposable:false, parts:[], note:'팔을 구부린 모습을 본뜬 글자로, 굽어서 끝까지 다다른 수 "아홉"을 나타내요.',
    word:{ text:'九月', meaning:'9월' } },
  { char:'十', meaning:'열', sound:'십', stroke:2, radical:'十', type:'지사', category:'숫자',
    decomposable:false, parts:[], note:'가로획과 세로획이 교차한 모습으로, 사방(동서남북)을 다 모은 완전한 수 "열"을 나타내요.',
    word:{ text:'十月', meaning:'10월' } },

  // ── 가족 ──
  { char:'父', meaning:'아비', sound:'부', stroke:4, radical:'父', type:'상형', category:'가족',
    decomposable:false, parts:[], note:'손에 돌도끼나 회초리를 들고 집안을 이끄는 모습을 본뜬 상형문자로, 가장의 권위를 나타내요.',
    word:{ text:'父母', meaning:'부모' } },
  { char:'母', meaning:'어미', sound:'모', stroke:5, radical:'毋', type:'상형', category:'가족',
    decomposable:false, parts:[], note:'두 손을 모으고 앉은 여자의 모습에 유방을 뜻하는 점 두 개를 더해 "어머니"를 나타낸 상형문자예요.',
    word:{ text:'母校', meaning:'모교' } },
  { char:'兄', meaning:'형', sound:'형', stroke:5, radical:'儿', type:'회의', category:'가족',
    decomposable:true, parts:[{char:'口',meaning:'입 구(말하다)'},{char:'儿',meaning:'어진사람 인'}],
    note:'집안에서 입(口)으로 먼저 말하며 이끄는 사람(儿)이라는 뜻에서 "형"이 됐어요.',
    word:{ text:'兄弟', meaning:'형제' } },
  { char:'弟', meaning:'아우', sound:'제', stroke:7, radical:'弓', type:'상형', category:'가족',
    decomposable:false, parts:[], note:'활이나 말뚝에 끈을 차례로 감아 내려가는 모습을 본떠 "순서, 차례"를 뜻하다가 손아래 형제인 "아우"를 가리키게 됐어요.',
    word:{ text:'兄弟', meaning:'형제' } },

  // ── 학교 ──
  { char:'校', meaning:'학교', sound:'교', stroke:10, radical:'木', type:'형성', category:'학교',
    decomposable:true, parts:[{char:'木',meaning:'나무 목'},{char:'交',meaning:'사귈 교(소리)'}],
    note:'나무(木)로 지은 건물에서 交(사귈 교)가 소리를 담당해요. "나무로 지어 아이들이 서로 사귀며 배우는 곳"으로 기억하면 좋아요.',
    word:{ text:'學校', meaning:'학교' } },
  { char:'敎', writer:'教', meaning:'가르칠', sound:'교', stroke:11, radical:'攴', type:'회의', category:'학교',
    decomposable:true, parts:[{char:'子',meaning:'아들 자(아이)'},{char:'攵',meaning:'칠 복(회초리로 치다)'}],
    note:'아이(子)를 회초리로 치며(攵) 이끈다는 뜻에서 "가르치다"가 됐어요. 이 글자는 한국 정자체(敎)와 일반 서체(教)의 모양이 조금 달라 획순 애니메이션은 일반 서체로 보여드려요.',
    word:{ text:'敎室', meaning:'교실' } },
  { char:'學', meaning:'배울', sound:'학', stroke:16, radical:'子', type:'회의', category:'학교',
    decomposable:true, parts:[{char:'冖',meaning:'덮을 멱(지붕)'},{char:'臼',meaning:'두 손 모양'},{char:'子',meaning:'아들 자(아이)'}],
    note:'지붕(冖) 아래에서 두 손(臼)으로 아이(子)를 가르치고 배우는 모습을 나타낸 글자예요.',
    word:{ text:'學生', meaning:'학생' } },
  { char:'生', meaning:'날', sound:'생', stroke:5, radical:'生', type:'상형', category:'학교',
    decomposable:false, parts:[], note:'땅 위로 새싹이 돋아나는 모습을 본뜬 상형문자로, "태어나다, 살다"를 뜻해요.',
    word:{ text:'生日', meaning:'생일' } },
  { char:'先', meaning:'먼저', sound:'선', stroke:6, radical:'儿', type:'회의', category:'학교',
    decomposable:true, parts:[{char:'之',meaning:'갈 지(발걸음)'},{char:'儿',meaning:'어진사람 인'}],
    note:'발걸음(之의 변형)이 사람(儿)보다 앞서 나아간다는 뜻에서 "먼저"가 됐어요.',
    word:{ text:'先生', meaning:'선생님' } },
  { char:'室', meaning:'집', sound:'실', stroke:9, radical:'宀', type:'회의', category:'학교',
    decomposable:true, parts:[{char:'宀',meaning:'집 면(지붕)'},{char:'至',meaning:'이를 지(다다르다)'}],
    note:'사람이 다다라서(至) 머무는 집(宀)의 안쪽 방을 뜻해요.',
    word:{ text:'敎室', meaning:'교실' } },

  // ── 방위 ──
  { char:'中', meaning:'가운데', sound:'중', stroke:4, radical:'丨', type:'지사', category:'방위',
    decomposable:false, parts:[], note:'네모(囗) 한가운데를 세로획(丨)으로 꿰뚫은 모습으로, 깃대가 진영 한가운데 꽂힌 모습에서 나왔다는 설도 있어요.',
    word:{ text:'中心', meaning:'중심' } },
  { char:'東', meaning:'동녘', sound:'동', stroke:8, radical:'木', type:'회의', category:'방위',
    decomposable:true, parts:[{char:'木',meaning:'나무 목'},{char:'日',meaning:'날 일(해)'}],
    note:'나무(木) 사이로 해(日)가 걸려 떠오르는 모습으로, 해가 뜨는 방향인 "동쪽"을 나타내요.',
    word:{ text:'東海', meaning:'동해' } },
  { char:'西', meaning:'서녘', sound:'서', stroke:6, radical:'襾', type:'상형', category:'방위',
    decomposable:false, parts:[], note:'새가 둥지에 깃들어 쉬는 모습을 본떠, 해가 지고 새가 깃드는 방향인 "서쪽"을 나타내요.',
    word:{ text:'西海', meaning:'서해' } },
  { char:'南', meaning:'남녘', sound:'남', stroke:9, radical:'十', type:'상형', category:'방위',
    decomposable:false, parts:[], note:'따뜻한 남쪽 지방에서 쓰던 악기 모양을 본뜬 글자에서 "남쪽"이라는 뜻이 나왔어요.',
    word:{ text:'南山', meaning:'남산' } },
  { char:'北', meaning:'북녘', sound:'북', stroke:5, radical:'匕', type:'회의', category:'방위',
    decomposable:true, parts:[{char:'匕',meaning:'사람이 뒤돌아선 모양'},{char:'匕',meaning:'또 다른 사람'}],
    note:'두 사람이 서로 등을 맞대고 있는 모습으로, "등지다"는 뜻에서 방향으로는 등지는 쪽인 "북쪽"을 나타내게 됐어요.',
    word:{ text:'北韓', meaning:'북한' } },
  { char:'外', meaning:'바깥', sound:'외', stroke:5, radical:'夕', type:'회의', category:'방위',
    decomposable:true, parts:[{char:'夕',meaning:'저녁 석'},{char:'卜',meaning:'점 복'}],
    note:'저녁(夕)에 거북점(卜)을 치면 평소와 다른, 예상 "바깥"의 조짐이 나온다는 데서 유래했어요.',
    word:{ text:'外家', meaning:'외가' } },

  // ── 사람과 크기 ──
  { char:'大', meaning:'큰', sound:'대', stroke:3, radical:'大', type:'상형', category:'사람·크기',
    decomposable:false, parts:[], note:'사람이 두 팔과 두 다리를 크게 벌리고 서 있는 모습을 본뜬 상형문자예요.',
    word:{ text:'大門', meaning:'대문' } },
  { char:'小', meaning:'작을', sound:'소', stroke:3, radical:'小', type:'상형', category:'사람·크기',
    decomposable:false, parts:[], note:'작은 점들이 나뉘어 흩어진 모습을 본뜬 상형문자로, "작다"는 뜻을 나타내요.',
    word:{ text:'大小', meaning:'대소(크고 작음)' } },
  { char:'人', meaning:'사람', sound:'인', stroke:2, radical:'人', type:'상형', category:'사람·크기',
    decomposable:false, parts:[], note:'옆에서 본 사람이 서 있는 모습을 본뜬 상형문자예요.',
    word:{ text:'韓國人', meaning:'한국인' } },
  { char:'女', meaning:'계집', sound:'여', stroke:3, radical:'女', type:'상형', category:'사람·크기',
    decomposable:false, parts:[], note:'두 손을 모으고 얌전히 앉아 있는 여자의 모습을 본뜬 상형문자예요.',
    word:{ text:'女子', meaning:'여자' } },
  { char:'王', meaning:'임금', sound:'왕', stroke:4, radical:'玉', type:'회의', category:'사람·크기',
    decomposable:true, parts:[{char:'三',meaning:'하늘·땅·사람'},{char:'丨',meaning:'뚫을 곤(꿰뚫다)'}],
    note:'하늘·땅·사람(三)을 하나로 꿰뚫는(丨) 존재라는 뜻에서 "임금"을 나타내게 됐다고 풀이해요.',
    word:{ text:'王國', meaning:'왕국' } },

  // ── 나라 ──
  { char:'國', meaning:'나라', sound:'국', stroke:11, radical:'囗', type:'회의', category:'나라',
    decomposable:true, parts:[{char:'囗',meaning:'에워쌀 위(영토)'},{char:'或',meaning:'혹 혹(창을 들고 지키다)'}],
    note:'창(戈)을 들고 사람과 땅(口, 一)을 지키는 모습(或)이 영토(囗)에 둘러싸인 "나라"를 나타내요.',
    word:{ text:'韓國', meaning:'한국' } },
  { char:'軍', meaning:'군사', sound:'군', stroke:9, radical:'車', type:'회의', category:'나라',
    decomposable:true, parts:[{char:'冖',meaning:'덮을 멱(둘러싸다)'},{char:'車',meaning:'수레 거(전차)'}],
    note:'전차(車)를 둥글게 둘러싼(冖) 모습으로, 전차 부대인 "군사"를 나타내요.',
    word:{ text:'軍人', meaning:'군인' } },
  { char:'民', meaning:'백성', sound:'민', stroke:5, radical:'氏', type:'상형', category:'나라',
    decomposable:false, parts:[], note:'옛 갑골문에서 유래를 두고 여러 설이 있는 상형문자로, 다스림을 받는 사람들인 "백성"을 나타내요.',
    word:{ text:'國民', meaning:'국민' } },
  { char:'韓', meaning:'나라이름', sound:'한', stroke:17, radical:'韋', type:'형성', category:'나라',
    decomposable:true, parts:[{char:'倝',meaning:'해돋을 간(소리)'},{char:'韋',meaning:'다룸가죽 위'}],
    note:'원래는 우물 난간을 뜻하던 글자인데, 소리를 빌려 나라 이름 "한(韓)"을 나타내는 데 쓰이게 됐어요.',
    word:{ text:'韓國', meaning:'한국' } },

  // ── 자연 ──
  { char:'山', meaning:'뫼', sound:'산', stroke:3, radical:'山', type:'상형', category:'자연',
    decomposable:false, parts:[], note:'세 개의 봉우리가 솟은 산의 모습을 본뜬 상형문자예요.',
    word:{ text:'山水', meaning:'산수' } },
  { char:'水', meaning:'물', sound:'수', stroke:4, radical:'水', type:'상형', category:'자연',
    decomposable:false, parts:[], note:'가운데 물줄기와 양옆으로 튀는 물방울을 함께 본뜬 상형문자예요.',
    word:{ text:'水曜日', meaning:'수요일' } },
  { char:'火', meaning:'불', sound:'화', stroke:4, radical:'火', type:'상형', category:'자연',
    decomposable:false, parts:[], note:'타오르는 불꽃의 모습을 본뜬 상형문자예요.',
    word:{ text:'火曜日', meaning:'화요일' } },
  { char:'木', meaning:'나무', sound:'목', stroke:4, radical:'木', type:'상형', category:'자연',
    decomposable:false, parts:[], note:'뿌리, 줄기, 가지를 뻗은 나무의 모습을 본뜬 상형문자예요.',
    word:{ text:'木曜日', meaning:'목요일' } },
  { char:'金', meaning:'쇠', sound:'금', stroke:8, radical:'金', type:'회의', category:'자연',
    decomposable:true, parts:[{char:'土',meaning:'흙 토'},{char:'亼',meaning:'모을 집'}],
    note:'흙(土) 속에 반짝이는 쇳덩이 알갱이(점 두 개)가 묻혀 있는 모습을 본떴어요. 성씨로 쓸 때는 "김"으로 읽어요.',
    word:{ text:'金曜日', meaning:'금요일' } },
  { char:'土', meaning:'흙', sound:'토', stroke:3, radical:'土', type:'상형', category:'자연',
    decomposable:false, parts:[], note:'땅 위에 흙무더기가 쌓인 모습을 본뜬 상형문자예요.',
    word:{ text:'土曜日', meaning:'토요일' } },
  { char:'日', meaning:'날', sound:'일', stroke:4, radical:'日', type:'상형', category:'자연',
    decomposable:false, parts:[], note:'해의 둥근 모양과 그 안의 흑점을 함께 본뜬 상형문자예요.',
    word:{ text:'日曜日', meaning:'일요일' } },
  { char:'月', meaning:'달', sound:'월', stroke:4, radical:'月', type:'상형', category:'자연',
    decomposable:false, parts:[], note:'초승달의 굽은 모양을 본뜬 상형문자예요.',
    word:{ text:'月曜日', meaning:'월요일' } },
  { char:'靑', writer:'青', meaning:'푸를', sound:'청', stroke:8, radical:'靑', type:'회의', category:'자연',
    decomposable:true, parts:[{char:'生',meaning:'날 생(돋아나다)'},{char:'丹',meaning:'붉을 단(우물 난간이 변형)'}],
    note:'풀과 새싹이 돋아나는(生) 색인 푸른빛을 나타내요. 정자체(靑)와 일반 서체(青)의 아랫부분 모양이 달라, 획순 애니메이션은 일반 서체로 보여드려요.',
    word:{ text:'靑年', meaning:'청년' } },

  // ── 생활 ──
  { char:'年', meaning:'해', sound:'년', stroke:6, radical:'干', type:'회의', category:'생활',
    decomposable:true, parts:[{char:'禾',meaning:'벼 화'},{char:'人',meaning:'사람 인(짊어지다)'}],
    note:'사람이 다 자란 벼(禾)를 짊어진 모습으로, 벼가 익어 거두는 한 번의 주기인 "한 해"를 나타내요.',
    word:{ text:'學年', meaning:'학년' } },
  { char:'萬', meaning:'일만', sound:'만', stroke:13, radical:'艸', type:'상형', category:'생활',
    decomposable:false, parts:[], note:'원래 전갈의 모습을 본뜬 상형문자였는데, 소리를 빌려 아주 큰 수 "일만"을 나타내는 데 쓰이게 됐어요.',
    word:{ text:'萬歲', meaning:'만세' } },
  { char:'門', meaning:'문', sound:'문', stroke:8, radical:'門', type:'상형', category:'생활',
    decomposable:false, parts:[], note:'좌우로 여닫는 두 짝의 문 모양을 본뜬 상형문자예요.',
    word:{ text:'大門', meaning:'대문' } },
  { char:'白', meaning:'흰', sound:'백', stroke:5, radical:'白', type:'상형', category:'생활',
    decomposable:false, parts:[], note:'해가 막 떠오르기 시작할 때의 흰 빛을 본뜬 상형문자라는 설이 있어요.',
    word:{ text:'白紙', meaning:'백지' } },
  { char:'長', meaning:'긴', sound:'장', stroke:8, radical:'長', type:'상형', category:'생활',
    decomposable:false, parts:[], note:'머리카락이 길게 자란 노인이 지팡이를 짚은 모습을 본뜬 상형문자로, "길다, 어른"을 뜻해요.',
    word:{ text:'長男', meaning:'장남' } },
  { char:'寸', meaning:'마디', sound:'촌', stroke:3, radical:'寸', type:'지사', category:'생활',
    decomposable:false, parts:[], note:'손목에서 맥박이 뛰는 곳까지의 한 마디 거리를 나타낸 지사문자로, 친척 사이의 촌수를 셀 때도 써요.',
    word:{ text:'四寸', meaning:'사촌' } },
];
